// <auto-generated />
using System;
using IlacTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IlacTakip.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250724153105_BasitSistem")]
    partial class BasitSistem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IlacTakip.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ad");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasColumnName("AktifMi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EPosta");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sifre");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("SonGirisTarihi");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Soyad");

                    b.HasKey("Id");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("IlacTakip.Models.Ilac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IlacId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IlacAdi");

                    b.Property<string>("BarkodNumarasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BarkodNumarasi");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Fiyat");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<DateTime?>("SonKullanmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("SonKullanmaTarihi");

                    b.Property<int>("StokMiktari")
                        .HasColumnType("int")
                        .HasColumnName("StokMiktari");

                    b.HasKey("Id");

                    b.ToTable("Ilaclar", (string)null);
                });

            modelBuilder.Entity("IlacTakip.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonelId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ad");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasColumnName("AktifMi");

                    b.Property<DateTime?>("IseBaslamaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("IseBaslamaTarihi");

                    b.Property<decimal>("Maas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Maas");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("Pozisyon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pozisyon");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Soyad");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefon");

                    b.HasKey("Id");

                    b.ToTable("Personeller", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
